FROM ubuntu:18.04

# fetch package lists
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update

# setup sudo and ubuntu user with sudo rights and no password
RUN apt-get install -y sudo
RUN adduser --disabled-password --gecos '' ubuntu && adduser ubuntu sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ubuntu
WORKDIR /home/ubuntu

# don't leave the locale as POSIX, otherwise we get the dreaded UnicodeDecodeError
ENV LANG=C.UTF-8

# install curl
RUN sudo apt-get install -y curl

COPY install.sh /home/ubuntu
RUN /home/ubuntu/install.sh
