name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Tag commit
      #if: github.ref == 'refs/heads/main'
      uses: tekumara/github-tagger@force-update
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "latest"

